package com.customcontentengine.adapter.bukkit;

import com.customcontentengine.domain.mechanic.MechanicBindingRegistry;
import com.customcontentengine.domain.mechanic.MechanicTrigger;
import com.customcontentengine.domain.registry.DefinitionRegistry;
import com.customcontentengine.internalapi.identity.CustomItemId;
import com.customcontentengine.internalapi.mechanic.MechanicId;
import java.util.List;
import java.util.Objects;
import org.bukkit.command.Command;
import org.bukkit.command.CommandExecutor;
import org.bukkit.command.CommandSender;

/**
 * Dev tool that dumps the loaded {@link DefinitionRegistry} item-to-mechanic bindings to the
 * command sender. Used by integration tests (Phase 0) to assert the registry generated by the
 * real server contains the expected definitions.
 *
 * <p>Emits one line per binding in the form
 * {@code [registry] item=<id> trigger=<key> mechanic=<id>}.</p>
 */
public final class DebugRegistryCommandAdapter implements CommandExecutor {
    private final DefinitionRegistry registry;

    public DebugRegistryCommandAdapter(DefinitionRegistry registry) {
        this.registry = Objects.requireNonNull(registry, "registry");
    }

    @Override
    public boolean onCommand(CommandSender sender, Command command, String label, String[] args) {
        MechanicBindingRegistry bindings = registry.mechanicBindings();
        for (String itemId : registry.itemsById().keySet()) {
            for (MechanicTrigger trigger : MechanicTrigger.values()) {
                List<MechanicId> mechanicIds = bindings.mechanicIdsFor(new CustomItemId(itemId), trigger);
                for (MechanicId mechanicId : mechanicIds) {
                    sender.sendMessage(
                            "[registry] item=" + itemId + " trigger=" + trigger.yamlKey() + " mechanic=" + mechanicId);
                }
            }
        }
        if (registry.itemsById().isEmpty()) {
            sender.sendMessage("[registry] no items defined");
        }
        return true;
    }
}
