package com.customcontentengine.integration.base;

import static org.junit.jupiter.api.Assertions.assertTrue;

import com.customcontentengine.integration.harness.PaperServer;
import java.nio.file.Files;
import java.nio.file.Path;
import java.time.Duration;
import java.util.function.Predicate;
import org.junit.jupiter.api.AfterAll;
import org.junit.jupiter.api.BeforeAll;

/**
 * Base class for all Paper integration tests (ADR-0013 / TEST_INTEGRATION_PLAN.md Phase 0).
 *
 * <p>Responsibilities:</p>
 * <ul>
 *     <li>Manage the Paper server lifecycle (one server per test class, started in
 *     {@code @BeforeAll} and stopped in {@code @AfterAll}).</li>
 *     <li>Provide thin utilities for sending commands, awaiting output, and asserting on the
 *     emitted server log.</li>
 *     <li>Provide {@link #assertRegistryContains(String, String)} to validate the
 *     {@code DefinitionRegistry} generated by the real server.</li>
 * </ul>
 *
 * <p>The plugin jar and Paper jar are supplied via the {@code customcontent.pluginJar} and
 * {@code customcontent.paperJar} system properties (configured by the Gradle
 * {@code integrationTest} task).</p>
 */
public abstract class BasePaperIntegrationTest {
    protected static final Duration SERVER_START_TIMEOUT = Duration.ofMinutes(6);
    protected static final Duration COMMAND_TIMEOUT = Duration.ofSeconds(30);

    protected static PaperServer server;
    private static Path serverDirectory;

    @BeforeAll
    static void startPaperServer() throws Exception {
        Path pluginJar = requiredPathProperty("customcontent.pluginJar");
        Path paperJar = requiredPathProperty("customcontent.paperJar");
        serverDirectory = Files.createTempDirectory("customcontent-paper-it-");
        PaperServer.prepareServerDirectory(serverDirectory, pluginJar);
        server = PaperServer.start(serverDirectory, paperJar);
        server.awaitOutput(line -> line.contains("Done ("), SERVER_START_TIMEOUT);
    }

    @AfterAll
    static void stopPaperServer() throws Exception {
        if (server != null) {
            server.close();
            server = null;
        }
        if (serverDirectory != null) {
            PaperServer.deleteRecursively(serverDirectory);
            serverDirectory = null;
        }
    }

    protected static Path serverDirectory() {
        return serverDirectory;
    }

    protected static void sendCommand(String command) throws java.io.IOException {
        server.sendCommand(command);
    }

    protected static void awaitOutput(Predicate<String> predicate, Duration timeout) throws InterruptedException {
        server.awaitOutput(predicate, timeout);
    }

    protected static boolean outputContains(String text) {
        return server.outputContains(text);
    }

    protected static String fullOutput() {
        return server.fullOutput();
    }

    /**
     * Validates that the registry loaded by the running server contains the given item bound to
     * the given mechanic. Relies on the {@code debugregistry} dev command emitting lines of the
     * form {@code [registry] item=<id> trigger=<key> mechanic=<id>}.
     */
    protected static void assertRegistryContains(String itemId, String mechanicId) throws Exception {
        sendCommand("debugregistry");
        awaitOutput(line -> line.contains("item=" + itemId), COMMAND_TIMEOUT);
        assertTrue(
                outputContains("item=" + itemId),
                () -> "Registry missing item: " + itemId + "%n%s".formatted(fullOutput()));
        assertTrue(
                outputContains("mechanic=" + mechanicId),
                () -> "Registry missing mechanic binding: " + mechanicId + "%n%s".formatted(fullOutput()));
    }

    protected static Path requiredPathProperty(String propertyName) {
        String value = System.getProperty(propertyName);
        if (value == null || value.isBlank()) {
            throw new IllegalStateException("Missing required system property: " + propertyName);
        }
        return Path.of(value);
    }
}
